### ISSUE TITLE
Update names of KVM OS types

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#1]
Append ` VM` to `Linux`, `BSD`, `Windows` and `SunOS` ostypes to indicate that these are KVM virtual machines.

Documentation (api docs and user guide) needs to be updated afterwards.

**Comment by mbag** [comment]
@dn0 should this change go into changelog? It doesn't seem to me as either bug or feature, or should we have another category for these kind of changes?

**Comment by dn0** [comment]
It's a feature :)
