### ISSUE TITLE
Snapshot size refresh after rollback

### ISSUE THREAD

**Issue by YanChii** [erigones/esdc-ce#105]
Hi,
after rollback of VM snapshot, it's displayed size in the GUI remains the same as before the rollback. But it should be zero again as the changes after snapshot have been dropped.
I expect the same applies also to older snapshots - their sizes should be refreshed.
Jan

**Comment by dn0** [comment]
Snapshot size is currently calculated periodically and we will keep it that way unless we change the underlying ZFS property for calculating the snapshot size (currently `written` attribute).
