### ISSUE TITLE
Behavior after user permission change is confusing

### ISSUE THREAD

**Issue by secult** [erigones/esdc-ce#108]
1. User is a UserAdmin in a datacenter that is not the main datacenter. 
2. User changes permission-related property on herself.
3. After clicking "Update", one gets immediately 403 Forbidden message.
(User was switched to _main_ datacenter and therefore cannot access _/dc*_ path. where she's not Admin).
The correct behavior may be that after permission related change, user should be redirected to url, where she has access (root url is sufficient).

**Comment by dn0** [comment]
Commit 0d4c80c7ffc01a31b14ce6fe18d8877e7af38903 merged
