### ISSUE TITLE
DC-bound UserAdmin is unable to create DC-bound groups

### ISSUE THREAD

**Issue by secult** [erigones/esdc-ce#109]

**Comment by ricco386** [comment]
If we do this we have two possibilities:

1. UserAdmin can create DC-bound groups and assign any permission to it. This way he can promote himself to any-type of Admin in our system. This sounds like security issue.

2. UserAdmin can create DC-bound groups without any permission, eg. he can not assign any permission to it. Which would mean he creates empty groups that does nothing. This sounds like creating unnecessary mess in the system.

The only use-case that comes to my mind is that UserAdmin would be able to create another DC-bound group with permission of UserAdmin, but again this does not make too much sense as that DC have such group with such permission, so he can add users to his group (and he is already capable of doing it).

So I am closing this bug as wont fix. If you feel this is wrong thing to do, please re-open it add your use case so we can discuss it.

**Comment by YanChii** [comment]
There's one more option: 
UserAdmin can assign only permissions that have been assigned to him. I don't see any security issue with this approach.
