### ISSUE TITLE
Increment SOA serial when updating DNS records

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#118]
+ Add ability to change domain types
+ Change default domain type to MASTER
+ Cleanup record model

**Comment by YanChii** [comment]
For DNS replication to external servers to be fully functional, these conditions have to be met:
1. IP address of the main DNS server(s) has to be visible from the slave
2. The external DNS server has to be listed in NS record of the synchronized zone
3. Config file pdns.conf in dns01 must have these lines altered:
   disable-axfr=no
   master=yes
   allow-axfr-ips=addr.of.the.extdns,addr.of.the.seconddns
4. The zone has to be in state MASTER
5. SOA serial has to be incremented to triger notify

The most problematic is the requirement 3. We need to find a way to automatize or workaround it. Maybe [this](https://doc.powerdns.com/md/authoritative/domainmetadata/#allow-axfr-from) can be the way (see 'AUTO-NS' settings).
