### ISSUE TITLE
Move Create DNS checkbox to non advanced section

### ISSUE THREAD

**Issue by ricco386** [erigones/esdc-ce#145]
When creating NIC for VM, move Create DNS check-box to non advanced section.

Reason for doing this is that we do create DNS record automatically for the first NIC that is added to VM. Which is a bit magic for user if he doesn't see this check box. If he removes the NIC and than try to re-create no DNS record is created. 

This way it would be more obvious that no DNS is created and also easier to amend if user want DNS record for that NIC (IP).

**Comment by dn0** [comment]
Closed via PR #147
