### ISSUE TITLE
Update PUT vm_manage to support forcible changing of vm.node in DB

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#154]
- document `force` parameter
- document new `node` parameter (what it does and that is only available for `SuperAdmin`)
- add `node` parameter: new node of VM (user has moved VM to another node manually)
   - check if user is `SuperAdmin`
   - check if node exists (and is attached in DC)
   - check if node is not the same as current node
- run existing vmadm get task on new compute node
- update callback to change compute node VM relation (vm.set_node()) after successful vmadm get + update active_json.

**Comment by mbag** [comment]
Merged in PR #158
