### ISSUE TITLE
Update backup functionality to store metadata on backup node

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#155]
- modify esbackup:
   - add support for saving metadata (provided via stdin)
      - esbackup ds-create
      - esdbackup file-create

      - Add parameters:
		- -m <file-path> parameter for metadata file
		- -j <json> parameter for VM JSON 
   - add support for deleting metadata 
      - esbackup ds-delete
      - esdbackup file-delete
    
      - Add parameters:
		- -m <file-path> parameter for metadata file

- modify vm_backup API call
   - add DB Backup field for storing metadata path
   - add support: for new esbackup parameters when creating and deleting backups

**Comment by ricco386** [comment]
@dn0 Update esdc-factory to create `/zones/backups/manifests`

**Comment by ricco386** [comment]
PR #164 has been merged and branch deleted.
