### ISSUE TITLE
IP addr database not refreshed after "es set /vm/<hostname> -force"

### ISSUE THREAD

**Issue by YanChii** [erigones/esdc-ce#168]
Hi,
when calling an update of VM configuration after manual changes using vmadm (es set /vm/<hostname> -force), the VM info is refreshed properly.. but the ESDC IP address database is not updated (considering there was an IP addr change). Therefore the new VM IP is treated as free and can be assigned to another host without a warning.
J.

**Comment by YanChii** [comment]
And also the old VM IP addr is not marked as free.

**Comment by dn0** [comment]
@YanChii Although we will fix this bug, please note, that this operation is not supported - any VM configuration change must be made via the Danube Cloud API or GUI. **Changing the VM configuration directly on the hypervisor is an unsupported operation.**

Also, I cannot reproduce the problem mentioned in the comment (*removing the association of old IP address with the VM*).

**Comment by dn0** [comment]
TODO: raise an exception on error and add `transaction.atomic` to the task.
