### ISSUE TITLE
Network traffic grows significantly with number of workers

### ISSUE THREAD

**Issue by secult** [erigones/esdc-ce#179]
Considerable amount of traffic flows through the celeryev exchange. It seems that the messages are amplified by the celeryev exchange and therefore we get quite a lot traffic even for small deployments.

**Comment by secult** [comment]
With every instance of an event Receiver (like as the one at que/bootsteps.py:245 and sio/monitor.py:63), a new queue with named celeryev.{random uuid} is created, which is subscribed to the celeryev exchange. For every erigonesd worker there's actually two subscriptions - there's the one at que/bootsteps, but one also at celery/bootsteps.py:403).

**Comment by secult** [comment]
The celery/bootsteps subscription is related to celery Gossip feature.

**Comment by dn0** [comment]
Resolved in PR #180
