### ISSUE TITLE
Danube latest: errors during install

### ISSUE THREAD

**Issue by Roelofp4r** [erigones/esdc-ce#238]
I have tried the "latest" USB installer to try Danube and struck the following errors:
1. esdc-ce-hn-latest.img.gz has an .img file with the name esdc-usb.img, so there is no possible way to see if it is the head node? 
2. the USB installer reports the following error just after the copyright notices of Joyent and Danube: "Warning: KCS error: ff" 
3. the installer fails on the setup script just after setting up the zones configuration. (i didn't have time to take a picture or write down the error) . But it results in omitting the "ask for admin email address" and other questions
4. after reboot the server is a plain SmartOS server without web interface and/ or zones. "vmadm list" gives no results

It seems to me that this danube thingie is still in early alpha stage?

**Comment by YanChii** [comment]
Hi Roelofp4r,
Danube Cloud is not in alpha stage.
1. What tool did you use to unpack the .gz? Using e.g. gunzip will keep the original name. But it seems that you are right - some archivers behave as you describe. We'll check them.
2. This is a SmartOS related issue. Quick google points to some unsupported hardware. What is the configuration of your server? You may also want to check the SmartOS hardware compatibility list.
3. Please upload `/var/log/prompt-config.log` and `/var/log/headnode-install.log` in a secure way (encrypt or delete the sensitive data if applicable). We'll take a look at it. This is very unusual behavior.
4. This may be related to 3. Or you were just too fast. The installation continues even after reboot. You can check it by `svcs -x`. But it continues to print the install messages.. so I expect you would notice that. Log files will tell us more.

Thank you for reporting the issues.
Jan

**Comment by Roelofp4r** [comment]
Hi Jan,

Thank you for your quick response! 
1. I used 7zip for windows to unpack the .img
2. It just saw someone with a simular error in the SmartOS mailing list, i will dig into it. My System is DL380Gen8, 1xE5-2620, P420i controller with 80GB RAM and all settings seem to be correct. 
3. I think i found the cause: because i was a little bit lazy i choose "dhcp" and not a fixed IP address. After reviewing the setup.sh file where i saw that the next steps are based on the primary IP-address i just started over again 15 minutes ago with a fixed primary address and all seemed to go fine.

**Comment by YanChii** [comment]
Hi @Roelofp4r,

Thank you for the feedback. If your installation suceeded, you probably should be fine even with that warning. 
The dhcp makes more sense in compute node install and less sense in head node install. But after the install, the head node becomes just another compute node with some service VMs which can be migrated to any other compute node. So there is a use case for dhcp even on HN. 
We'll think about it.. and how to make the installer more intuitive in this case. 
I've created an issue for this #240. We can move the conversation there if needed.

Jan
