### ISSUE TITLE
Description in image list should be hyperlink to image doc

### ISSUE THREAD

**Issue by YanChii** [erigones/esdc-ce#239]
Currently, this is implemented only in page for remote image download. But once the image is downloaded, there's no way to get to the documentation (like what mdata are supported, deploy instructions, etc). There's not even the easy way of knowing which image I'm looking at because GUI does not display image UUID.
Jan

**Comment by dn0** [comment]
The description in image list (GUI) is a hyperlink pointing to the image documentation.

**Comment by YanChii** [comment]
Negative. 
Just click on Datacenter -> Images and verify for yourself. (Don't click on Import disk Image from repository)

**Comment by dn0** [comment]
Ou, I see. This is a simple thing to add.
