### ISSUE TITLE
Reveal snapshot and backup IDs

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#24]
Lets show the user actual snapshot names and backup paths in the API. The idea of this change is to enable users to easily identify certain snapshots/backups on the FS, which might be helpful in some (disaster) situations.

Suggested read-only attributes (let's discuss this first):

- Snapshot: `id` - `Snapshot.zfs_name`
- Backup: `file_path` - `Backup.file_path`

(This is a really simple change - 2 lines of code)

**Comment by ricco386** [comment]
PR #37 closes this issue.
