### ISSUE TITLE
Add platform upgrade command

### ISSUE THREAD

**Issue by YanChii** [erigones/esdc-ce#289]
`esdc-platform-upgrade-diskboot`
```
Usage:   ./esdc-platform-upgrade-diskboot <new_platform_version> [--keep-smf-db]
Example: ./esdc-platform-upgrade-diskboot 20170624T192838Z
Args:
  --keep-smf-db         don't clear SMF database (useful if you don't want to loose
                        your manual changes to any SMF service properties)
```
`esdc-platform-upgrade-usbboot`
```
Usage:   ./esdc-platform-upgrade-usbboot <new_esdc_version>
Example: ./esdc-platform-upgrade-usbboot v2.6.7
```
The whole upgrade procedure can be managed like this:
```
cat /opt/erigones/bin/esdc-platform-upgrade
#!/bin/bash

if beadm list -H | grep -q dcos-; then
    /opt/erigones/bin/esdc-platform-upgrade-diskboot $PLATFORM_VER
elif /bin/bootparams | grep -q "^netboot=true"; then
    echo "This node is network booted. Nothing to do."
    exit 1
else
    /opt/erigones/bin/esdc-platform-upgrade-usbboot $ESDC_VER
fi
```

**Comment by YanChii** [comment]
The one thing that would be nice to have is to have a way to translate version numbers into the platform versions (e.g. 2.6.7 -> 20170624T192838Z).
Now, the USB upgrade expects ESDC version number and DISK upgrade requires platform version number.

Proposals:
1. Have the "translation table" directly in the disk upgrade script that selects the right platform version from ESDC version.
2. Provide some way to find it out from the internet (I didn't find the way for this so far).
3. Download whole ESDC image according to the version specified and extract the platform from it (quite ineffective).
4. Leave it as is - DISK upgrade requires platform number.
5. Allow only upgrades to the latest version (e.g. keyword `latest` can be specified instead of version).

My preference is `5` or `4`.

J.

**Comment by dn0** [comment]
Accepting the `latest` keyword is a good idea, but we should also accept versions.

I like the translation table idea (and we are already downloading the platform from the internet):

I'll rather explain it in code with this simple (**working**) example:

```bash

ESDC_VERSION_MAP_URL="https://download.erigones.org/esdc/factory/platform/esdc-version-map.json "
esdc_version="2.6.7"
esdc_search_version="${esdc_version//.}"
pi_version=""

while [[ -n "${esdc_search_version}" ]]; do
     pi_version="$(/opt/local/bin/curl -m 5 -s ${ESDC_VERSION_MAP_URL} | json "${esdc_search_version}")"

    if [[ -z "${pi_version}" ]]; then
        esdc_search_version="${esdc_search_version%?}"
    else
        break
    fi
done

[[ -z "${pi_version}"  ]] && die()...

```
