### ISSUE TITLE
Unable to backup LX zone

### ISSUE THREAD

**Issue by marcheschi** [erigones/esdc-ce#295]
Hi
I do not know if it is a general problem or mine.
I have an HN and a CN, 
A lx zone on HN and I want to backup it to CN , 
Althought the either hn and cn have the backup flag , I'm not able to select for backup.
Thank you
Paolo

**Comment by dn0** [comment]
@marcheschi is the backup node and its storage attached into the virtual datacenter?
(https://docs.danubecloud.org/user-guide/gui/datacenters/nodes.html#attaching-a-compute-node)

**Comment by marcheschi** [comment]
I think so :
![screenshot-2017-11-16 danube cloud_1](https://user-images.githubusercontent.com/3910408/32900538-f6f079f2-caed-11e7-9544-bedaa96c7885.png)

**Comment by dn0** [comment]
@marcheschi OK, that looks good.

You just need to create a backup definition for the VM: https://docs.danubecloud.org/user-guide/gui/servers/backups.html#backup-definitions

Do you see the backup nodes in this screen: https://docs.danubecloud.org/user-guide/_images/backup_definition_update.png?

**Comment by marcheschi** [comment]
That's exactly the problem I do not see the nodes in that screen:
![image](https://user-images.githubusercontent.com/3910408/32901493-38ad5b60-caf0-11e7-9bbe-3776c6e7eeef.png)

**Comment by dn0** [comment]
OK. I'm sorry for the confusion. The backup capability on the compute node is not enabled. The backup icon for a backup node must be blue in that screen.

You need to first enable the backup functionality here: https://docs.danubecloud.org/user-guide/gui/nodes/details.html#managing-a-compute-node

**Comment by marcheschi** [comment]
Great, I did not find the flag.
It is super !

Thank you
Paolo

**Comment by dn0** [comment]
Great. You're welcome.
