### ISSUE TITLE
Console is not working with Firefox 57

### ISSUE THREAD

**Issue by marcheschi** [erigones/esdc-ce#297]
Hi
Linux KVM console show only the screen console on firefox 57, 
but is not possible to interact with (for example login or issue commands ).
It works fine with google chrome instead.
Thank you
Paolo

**Comment by dn0** [comment]
Hi Paolo,

Please try to click on the magnet icon in the console -> that should catch all keyboard and mouse events and send them to the VM. More info here: https://docs.danubecloud.org/user-guide/gui/servers/console.html

**Comment by marcheschi** [comment]
Yes that's right, in chrome it works without the magnet.
Thank you 
Paolo
