### ISSUE TITLE
Problems using es

### ISSUE THREAD

**Issue by marcheschi** [erigones/esdc-ce#299]
Hi
I'm trying to use  the es utility from the head none but the default 8000 port on the zone seems closed
with nmap 
PORT    STATE SERVICE
22/tcp  open  ssh
80/tcp  open  http
443/tcp open  https

the https port works .

I think the script must be aware of this.
Paolo

**Comment by dn0** [comment]
@marcheschi The *es* downloaded from https://docs.danubecloud.org/api-reference/es.html cannot know the address of your installation and you have to modify the `API_URL` described in the document. But you're right. We will change the default value to something more meaningful.

However, if you download *es* from inside your Danube Cloud installation (Go to Support -> API Documentation -> es. The script download from there should already have the `API_URL` set correctly.

**Comment by dn0** [comment]
The es available from https://docs.danubecloud.org/api-reference/es.html  was changed to have `API_URL = 'https://127.0.0.1/api'`
