### ISSUE TITLE
vm.log: No such file or directory

### ISSUE THREAD

**Issue by marcheschi** [erigones/esdc-ce#300]
Hi 
After doing some experiment I noticed a lot of messages like this:
logadm: Warning: /zones/b0b9109a-7522-480e-a9b3-da79caa8057b/root/tmp/vm.log.0: No such file or directory
logadm: Warning: /zones/b0b9109a-7522-480e-a9b3-da79caa8057b/root/tmp/vm.log: No such file or directory

Where the uid is non existent anymore.
I think that when a migration or cancellation occurs the zone uuid is not removed from some logadm task.

Thank you
Paolo

**Comment by dn0** [comment]
Related to upstream issue https://github.com/joyent/smartos-live/issues/319

**Comment by dn0** [comment]
We have to fix in the SmartOS platform.
