### ISSUE TITLE
Missing default DNS entry 

### ISSUE THREAD

**Issue by YanChii** [erigones/esdc-ce#301]
After the instalation, there is DNS entry `ns1.local` of type `NS` for all default domains. But there's no `A` record for `ns1.local`.
```
### 10.0.60.163 is dns01 in lab DC instalation ###
> dig @10.0.60.163 -t ns local +short
ns1.local.
> dig @10.0.60.163 -t ns ns1.local +short
```
But there's a `dns01.local` entry that should be referenced (instead of `ns1.local`).
```
> dig @10.0.60.163 -t a dns01.local +short
10.0.60.163
```

To correct it, we have several options:
1. Add new `ns1.local` as `CNAME` to `dns01.local`
2. Rename `ns1.local` `NS` entry to `dns01.local` (and also in `SOA` record)

Jan

**Comment by dn0** [comment]
IIRC Option 1 is not completely valid - having CNAMEs pointing to NS records is discouraged by some RFC.

I suggest that we create an A record after the first initialization of the mgmt VM - PR #307
