### ISSUE TITLE
Clone image 

### ISSUE THREAD

**Issue by marcheschi** [erigones/esdc-ce#302]
Hi 
is there a way to clone an existing image , in order to create a template, to replicate on other nodes?
I mean, I build a linux or native, or Lx image with my added software , I save it as an image template, and later 
I can customize it, with new parameters to clone it to another node or put in an image repository?
Thank you
Paolo

**Comment by dn0** [comment]
Every image you create in Danube Cloud (via [VM snapshots](https://docs.danubecloud.org/user-guide/gui/servers/snapshots.html#image-create)) is stored on the local image server (img01).

You can use the new image to create another VM, boot it, customize it, create a snapshot and create a new image from the snapshot.

**Comment by marcheschi** [comment]
Great 
Danubecloud is Awesome!!
