### ISSUE TITLE
No free IP adding Network or network range

### ISSUE THREAD

**Issue by marcheschi** [erigones/esdc-ce#312]
Hi
I'm trying to add a network or a network range to the usable networks, in order to create server associated to a specific net.
![image](https://user-images.githubusercontent.com/3910408/33204137-cf952c52-d102-11e7-87b8-c64d438f5f7a.png)

A you can see there is no IPs in specific ranges.

Thank you 
Paolo

**Comment by dn0** [comment]
Hi Paolo,

Just click on the subnet link in the network list and there you can add IP addresses -> https://docs.danubecloud.org/user-guide/gui/datacenters/networks.html#network-ip-addresses
