### ISSUE TITLE
Zones creation requires vCPU set to 1 or greater.

### ISSUE THREAD

**Issue by DigitalOzUT** [erigones/esdc-ce#336]
When creating a SunZone or LinuxZone. The GUI now requires a vCPU. This field can no longer be set to zero.

**Comment by dn0** [comment]
This was always the case, but it will change in 3.0. For more information please see Issue #296 and PR #332

**Comment by DigitalOzUT** [comment]
How are you able to do it in the Admin Datacenter? None of the Danube core VMs are using vCPUs for the zones, ex.. DNS, IMAGE, CFGDB.

--
Jason Spencer
Oz Technologies
801-923-3876
http://oztech.io

**Comment by DigitalOzUT** [comment]
Thanks for the info. Anxiously awaiting version 3.

--
Jason Spencer
Oz Technologies
801-923-3876
http://oztech.io
