### ISSUE TITLE
Warning about unavailable nodes does not go away after node becomes available

### ISSUE THREAD

**Issue by YanChii** [erigones/esdc-ce#35]
Hi,
in GUI serverlist (/servers), if some node is unavailable, the following message appears on the top: "Some servers are not visible or accessible, because some compute nodes are not in online state. Servers are kept untouched. Full server control will be possible as soon as the compute nodes return to online state".

But when the node becomes reachable again and status of all nodes is green, the above message does not go away until the page is manually reloaded.

Also when any node becomes unavailable, the message does not appear until page is reloaded.

**Comment by dn0** [comment]
The fix should be simple:
- a CSS class must be added to the message boxes
- an `if` or `switch/case` block should be added to `node_status_update()` and depending on the new status the related message box can be hidden or shown (in case the element is found)

**Comment by mbag** [comment]
@dn0  In first point you mention, that CSS class must be added to the message boxes, did you mean that we need to create new CSS class? Because messages currently have class="box". If the point of this new class is to identify message boxes so they can be found, would it make sense to add `id` attribute?

**Comment by dn0** [comment]
@mbag Yes, we need a new CSS class to identify the node_is_not_available message boxes.
We also need to have these boxes always displayed even if the node is currently OK (so the JS can show it).
