### ISSUE TITLE
Manual update process v3.0.0-rc1 admin password broken GUI

### ISSUE THREAD

**Issue by DigitalOzUT** [erigones/esdc-ce#352]
When using the manual process to upgrade from 2.6.7 to version 3.0.0-rc1 on management vm, breaks the current Admin password for the GUI. I have testing the manual upgrade process 3 times, admin password is not accepted after each upgrade. Resets the password back to the changeme.

**Comment by dn0** [comment]
Hi @DigitalOzUT 
We will need more information regarding this issue. The manual update procedure was tested in several environments and we never encountered this kind of problem.

Did you run only the `bin/esdc-git-update` command?

Output from the command could shed more light on this strange problem. The output from the update script should be stored in `/opt/erigones/var/log/update*.log` files. The most important would be the `update_deploy.${COMMIT_ID}.log` log
(3.0.0-rc1 has commit id `78e6860acbd3c44eaea6e3f8dbed9eb02cfda70a`)

**Comment by DigitalOzUT** [comment]
This was my mistake. I was unaware that an employee did some testing and set the password to the default and did not change it back to what I had set it to. I will close this out.
