### ISSUE TITLE
Zones creation still requires vCPU 3.0.0-rc1

### ISSUE THREAD

**Issue by DigitalOzUT** [erigones/esdc-ce#356]
Testing the 3.0.0-rc1, it still requires zones to have a vCPU associated with it. This is a big issue, as there is no way to over provision the vCPUs. Is this still on track to be fixed in the 3.0.0 release?

**Comment by dn0** [comment]
You can overprovision vCPUs also in DC < 3.0, you just have to [change the compute node coefficient](https://docs.danubecloud.org/user-guide/gui/nodes/details.html#managing-a-compute-node) to a number higher that 1.

----

In 3.0.0-rc1, if you uncheck the [VMS_VM_CPU_CAP_REQUIRED](https://docs.danubecloud.org/user-guide/gui/datacenters/settings.html?highlight=vms_vm_cpu_cap_required) setting in your virtual datacenter settings you can set the vCPUs server parameter of SunOS and Linux zones to **0**. This will have two effects:
1. The compute node's free vCPU resource counter will not change.
2. There will be no `cpu_cap` set on the zone -> the zone can potentially use all CPU power of the compute node. You can find more information about `cpu_cap` here: https://docs.danubecloud.org/api-reference/api/vm_define.html or in issue #296

**Comment by DigitalOzUT** [comment]
No CPU_CAP on zones? Couldn't that have some adverse affects? A malicious user or a zone with a run away process could bring down a compute node. Maybe I am missing something, but I guess over provisioning CPUs is probably the safest bet? Thanks for getting back to me on this. Figuring out the best solutions to use all of the resources of a node.

**Comment by dn0** [comment]
If you don't trust your users or run some untrusted application inside zones you should rather set the vCPUs attribute (even if it is a very high number), which will set the cpu_cap.

CPU_CAP should be disabled only if you need to provide maximum cpu power to your zones. I think that the Fair Share Scheduler should take care that the compute node does not go down and other processes and VMs get some CPU shares too. But your should test this first. For example, disabling CPU_CAP makes sense if you run CPU-intensive computation inside your zone.

**Comment by DigitalOzUT** [comment]
Thank you for the quick response. So I was on the right track with over provisioning. We provide computer time to a few local high schools. I would rather avoid the possibility of a student causing issues. Really appreciate your time and help.
