### ISSUE TITLE
logadm not removing deleted vms from config file

### ISSUE THREAD

**Issue by DigitalOzUT** [erigones/esdc-ce#366]
I keep getting emails containing errors every hour on node that I have deleted vms from. The emails refer to No such file or directory
[root@node02 /usr/sbin]# logadm -n
logadm: Warning: /zones/f07c0927-49aa-43d2-a7c1-f937c9902236/root/tmp/vm.log: No such file or directory
logadm: Warning: /zones/f07c0927-49aa-43d2-a7c1-f937c9902236/root/tmp/vm.log.0: No such file or directory
logadm: Warning: /zones/ecdca6b3-6b0e-4ce3-98d4-cdbcc9b66066/root/tmp/vm.log: No such file or directory
logadm: Warning: /zones/ecdca6b3-6b0e-4ce3-98d4-cdbcc9b66066/root/tmp/vm.log.0: No such file or directory
logadm: Warning: /zones/62fce02d-0f7e-40a8-b7b4-b8c6b228029e/root/tmp/vm.log.1: No such file or directory
logadm: Warning: /zones/62fce02d-0f7e-40a8-b7b4-b8c6b228029e/root/tmp/vm.log.0: No such file or directory
logadm: Warning: /zones/62fce02d-0f7e-40a8-b7b4-b8c6b228029e/root/tmp/vm.log: No such file or directory
logadm: Warning: /zones/d4594bbc-cdbe-44b8-8d7e-a37a532fcac7/root/tmp/vm.log: No such file or directory

Each of theses are deleted VMs. manually running logadm -r I am able to remove the entries from the /etc/logadm.conf. When deleting a VM, logadm must remove it from the logadm.conf

**Comment by dn0** [comment]
Which platform version is this?

This was already reported to the upstream https://github.com/joyent/smartos-live/issues/319 and should be fixed in the latest platform
