### ISSUE TITLE
Unable to start Zabbix VM network statistics monitoring

### ISSUE THREAD

**Issue by Kiwwiaq** [erigones/esdc-ce#369]
Fresh installation of Danube Cloud "head node" from `esdc-ce-hn-3.0.0-rc4.img`, global zone is not able to start service `svc:/application/zabbix/vm-network-monitor:default`

`[ Apr  7 12:35:14 Executing start method ("/opt/zabbix/etc/scripts/vm-network-monitor"). ]`
`Can't locate Data/Dumper.pm in @INC (@INC contains: /usr/perl5/site_perl/5.12/i86pc-solaris-64int /usr/perl5/site_perl/5.12 /usr/perl5/5.12/lib/i86pc-solaris-64int /usr/perl5/5.12/lib .) at /opt/zabbix/etc/scripts/vm-network-monitor line 60.
BEGIN failed--compilation aborted at /opt/zabbix/etc/scripts/vm-network-monitor line 60.`
`[ Apr  7 12:35:14 Stopping because service exited with an error. ]`

Perl module `Data::Dumper` is missing in OS Perl. Module is not used in code right now. Can be commented out to enable service.

Is this a typo?

**Comment by dn0** [comment]
Thanks for reporting this. Probably related to https://smartos.org/bugview/OS-6563

We haven't touch the monitoring scripts for a long time. Must be something we've forgotten if it works without the module...

**Comment by dn0** [comment]
In addition, the *"put Perl on diet"* change also affects `/opt/zabbix/etc/scripts/zabbix_arcstat`.
