### ISSUE TITLE
svc:/application/zabbix/vm-cpu-monitor:default exited with status 29

### ISSUE THREAD

**Issue by Kiwwiaq** [erigones/esdc-ce#375]
Hi,

After the upgrade to latest v3.0.0, I noticed a possible monitoring script bug:
`2018-05-14T13:53:22+00:00 node01 svc.startd[8]: [ID 694882 daemon.notice] instance svc:/application/zabbix/vm-cpu-monitor:default exited with status 29`

This issue is as often as service is restarted.
`[ May 14 14:01:25 Executing start method ("/opt/zabbix/etc/scripts/vm-cpu-monitor"). ]
Illegal division by zero at /opt/zabbix/etc/scripts/vm-cpu-monitor line 121, <PRSTAT> line 5.
[ May 14 14:01:36 Stopping because service exited with an error. ]`

`# /opt/zabbix/etc/scripts/vm-cpu-monitor
Illegal division by zero at /opt/zabbix/etc/scripts/vm-cpu-monitor line 121, <PRSTAT> line 6.`

I believe, that problem is on line 116 of the monitoring script. I am using a couple of LX zones.
`next if $cpu_stats{$zonename}->{'type'} eq 'OS';`
When I modify to following, I believe the script behave as should:
`next if $cpu_stats{$zonename}->{'type'} eq 'OS' || $cpu_stats{$zonename}->{'type'} eq 'LX';`

Maybe it would be the best to check, if not "KVM", instead of if "OS" or "LX".

I started to use LX zones only after update to v3.0.0, so it is most probably not related to code version at all.

Kind regards,
Ivan

**Comment by dn0** [comment]
Thanks for the bug report
