### ISSUE TITLE
Manual image import problem

### ISSUE THREAD

**Issue by YanChii** [erigones/esdc-ce#376]
Hi,

When doing full DC reinstall, including the management virtuals, I back up images from `img01` and then copy them back to new `img01` VM. 
But at the final step (click import when displaying local image repository), I've got following error:
```
Image file URL is unreachable (HTTPConnectionPool(host='10.100.10.103', port=80): Read timed out. (read timeout=5)).
```
The IP address is correct (img01) and the port is reachable from inside of `img01`, from the node and also from the `mgmt01`.

Do you have an idea what is going on?

Thx.
Jan

**Comment by dn0** [comment]
Not enough information to reproduce the problem. Please reopen if it happens again.
