### ISSUE TITLE
boot hangs on supermicro X11SRA-RF

### ISSUE THREAD

**Issue by xmerlin** [erigones/esdc-ce#379]
Hello,
I've tried to boot 3.0 with a supermicro X11SRA-RF + Xeon W-2145 Skylake W and it hangs.

Last messages in verbose boot mode:

`ramdisk0 at root`
`ramdisk0 is /ramdisk`
`root on /ramdisk:a fstype ufs`

**Comment by YanChii** [comment]
Hi @xmerlin 

This looks like a SmarOS HW compatibility issue. Therefore it needs to be reported directly to SmartOS developers. You can try to look at this thread where we tried to debug Kaby Lake boot:
https://github.com/joyent/smartos-live/issues/727

Then you may report it directly here:
https://github.com/joyent/smartos-live/issues

When reporting, try to enable verbose boot (`-v` in the boot kernel line), maybe it gives you more info to report.

Jan

**Comment by xmerlin** [comment]
FYI the bug is marked as solved in smartos (#727) and the fix is already integrated in illumos.
The bug affects a large amount of machines ..so ..when do you plan to integrate it in danube cloud?

**Comment by YanChii** [comment]
Hi @xmerlin 

Yes, we've also helped with the testing.
We will investigate the effects on Danube Cloud installation. We'll let you know.

Jan

**Comment by YanChii** [comment]
Sorry, I've forgot to write here about the new version. The bug should be fixed with new 4.0+ releases.
