### ISSUE TITLE
Web Management Server not going online

### ISSUE THREAD

**Issue by bootsie123** [erigones/esdc-ce#380]
Hi. For some reason after installing Danube Cloud I'm unable to reach the web management server from the IP address I specified.

> 192.168.1.160

I'm pretty new to Danube Cloud so excuse me for my lack of terminology. The rest of the parts of the server which connect seperatly to the network and show up as a different IP addresses are somewhat working. 

> 161 is not pingable
> 162 is pingable, doesn't display anything
> 163 is pingable, get requests are accepted and show Danube Cloud version info
> 164 is pingable, doesn't display anything

So yeah. I was wondering what might be causing this and I could solve this. I'm going to assume that you'll need some logs to further help me so let me know which ones you need and I'll send them. Thanks!

**Comment by YanChii** [comment]
Hi @bootsie123 
It looks like the `mgmt01` VM was not deployed correctly. The reason for that can be found in ```/var/log/headnode-install.log``` on the hypervisor (SmartOS). I've seen it mostly happen on the very slow hardware or with very unusual inputs during the install prompt. 

The simplest way how to retry the creation of failed management VMs is to delete the failed ones (in this case `mgmt01`) using the `vmadm` command (if the VM exists) and reboot the server.

If the problem persists, please send us the errors from the `headnode-install.log`.

Jan

**Comment by dn0** [comment]
Stale issue. Please reopen if problem happens again.
