### ISSUE TITLE
Rename the "Freeze VM" button

### ISSUE THREAD

**Issue by YanChii** [erigones/esdc-ce#388]
Users have reported that the `Freeze` button name is very confusing. Freeze suggests saving the running VM state to disk to be able to resume it later. The current freeze functionality itself is good but it should be renamed.

**Comment by YanChii** [comment]
One proposal is to rename it to `Lock`.

**Comment by dn0** [comment]
`Locked` is already used when VM is being replicated or migrated.

**Comment by dn0** [comment]
@YanChii What about removing the button completely (at least from the GUI)?

**Comment by YanChii** [comment]
After reconsideration, I agree that it probably doesn't need to be in the GUI. API presence si fine.
