### ISSUE TITLE
Edit buttons should be more intuitive

### ISSUE THREAD

**Issue by secult** [erigones/esdc-ce#39]
Users are uncertain how to edit items ( VMs, Nodes etc).
![image](https://cloud.githubusercontent.com/assets/4550814/21674178/e3e778ec-d32c-11e6-8a80-bdaddbe496c5.png)
 
It may be beneficial to redesign, rethink the button, or move it somewhere else.

**Comment by ricco386** [comment]
After few mock ups, team has agreed on design:

```<button class="button mini"><i class="icon-pencil"></i> Edit</button>```
