### ISSUE TITLE
Create DC CentOS RPM repository

### ISSUE THREAD

**Issue by YanChii** [erigones/esdc-ce#399]
Obsolete `cloud-init` in CentOS base contains a bug that causes VMs to freeze forever during boot. This bug is here from the beginning but with new platform became more apparent, hiting the race condition 3/4 of all boots.

Therefore we should release the new version of `cloud-init` rpm because upstream is already fixed. I'll try to contact also CentOS bugzilla.

**Comment by YanChii** [comment]
https://bugs.centos.org/view.php?id=15799

**Comment by dn0** [comment]
-> esdc-factory

**Comment by YanChii** [comment]
After `metadata` service fix in the new SmartOS platform, this bug is no longer causing problems. We can wait for `cloud-init` rpm gets upgraded in the CentOS itself.
Closing this.
