### ISSUE TITLE
Erigonesd-beat fails to start when database unavailable

### ISSUE THREAD

**Issue by YanChii** [erigones/esdc-ce#40]
When postgresql database is unreachable (or login fails), the erigonesd-beat crashes. After crash, the service stays down. Instead, it should go into infinite connect loop waiting for the database because this can be only temporary problem.

**Comment by YanChii** [comment]
The same problem also applies to all gunicorn daemons (esdc@gunicorn-api esdc@gunicorn-gui esdc@gunicorn-sio) - when a database disappears, they fail with exit status 0 and stay down.

**Comment by YanChii** [comment]
Solved. It was systemd dependency in service file.
```Requires=postgresql-9.5```
When postgres was stopped, all services went down with it. It also explains exit status 0.
Changing Requires in factory repo.
Closing issue as fixed.

**Comment by dn0** [comment]
You can start standalone erigonesd-beat by running: `bin/erigonesd mgmt beat`

**Comment by secult** [comment]
The correct solution would be: If the celery beat finishes with a non-zero exit code, the process manager should restart it. 
To achieve this functionality, we have to cherry pick one bugfix in celery project, coming with version 4 in celery, 
[exactly this commit](https://github.com/celery/celery/commit/a0c3c129762c2a2543a4770c39b5f5b3e0c48f73).
