### ISSUE TITLE
Upgrade to 4.0 beta - ansible issue

### ISSUE THREAD

**Issue by YanChii** [erigones/esdc-ce#408]
During upgrade, the command 
```/opt/erigones/bin/ctl.sh deploy --update```
fails to upgrade ansible because it needs to have `PyNaCl` installed first.

New installations have solved it by placing this requirement before ansible install:
https://github.com/erigones/esdc-ce/pull/407/files#diff-97d6fce8f1d9759e88d0fea21685e653R21

Solution for upgrades can be one of these:
1. uninstall ansible prior to upgrading (if version <= `v3.0.0`, then `pip uninstall ansible`)
2. install `PyNaCl` before upgrading requirements

I'm not sure however where to put this code.

Any ideas?

**Comment by dn0** [comment]
This problem is not related to `PyNaCl`, going to debug this...

**Comment by dn0** [comment]
@YanChii Here is a potential fix - #417 (needs testing)
