### ISSUE TITLE
Fix DELETE /task/(task_id)

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#42]
The `que.utils.delete_task()` is broken (celery inspection of a task candidate for deletion). We should fix this and make the `DELETE /task/(task_id)` available for every PENDING task in the system.

The testing should also include use cases involving task cleanup (revoked tasks).

Target branch: v2.4

**Comment by secult** [comment]
Related to `queue` inspection done by the `que.utils.delete_task()` function:
In case the task is not in the queue, and the worker is not responding, there are at least two cases when the task is running even though the inspector doesn't know about it:
1. Few seconds after the rabbitmq server is restarted, the queue is not active and therefore the inspector doesn't see any acknowledged running task there.
2. When the worker's master process is shutting down (SIGTERM) and the task is running on a child process, the master process is detached from the queue already and it does not report about the task anymore. However, after the task is done, the child process reports about it's status correctly.

**Comment by dn0** [comment]
Although this work looks nice, I'm closing this issue for now. We can re-open this issue later (probably when upgrading celery).
The reason is that we currently cannot switch to `CELERY_ACKS_LATE = True`.
