### ISSUE TITLE
Install Docker Images

### ISSUE THREAD

**Issue by marcheschi** [erigones/esdc-ce#424]
Hi
This is a feature request.
Docker is a de facto standard in VM, a lot of softwares are delivered as Docker images, and it could be a nice extension to  Danube Cloud, 
Smartos can do that by using LX zones, and it works as shown here:
[Docker on Smartos](https://blog.jasper.la/docker-on-smartos-the-harder-way.html)

`# imgadm sources --add-docker-hub`
`Added "docker" image source "https://docker.io"`
`# imgadm import redis:3`
`Importing 0348076a-36c1-fc04-a0fb-bccdbf4c2fd8 (docker.io/redis:3) from "https://docker.io"
Gather image 0348076a-36c1-fc04-a0fb-bccdbf4c2fd8 ancestry
Must download and install 6 images
Downloaded image 66b6b062-a045-32bd-b7c2-b0381f3d7c68 (99.0 B)                                                                                                                                
Downloaded image 0348076a-36c1-fc04-a0fb-bccdbf4c2fd8 (420.0 B)                                                                                                                               
Downloaded image bdc38c41-d240-9538-95b1-5a8432852ab9 (1.7 KiB)                                                                                                                               
Downloaded image 923723d6-60c4-fdec-16f9-ed1e5970f8ee (919.2 KiB)                                                                                                                             
Downloaded image 36597173-2079-e74d-04c9-318e0151d5cb (5.6 MiB)                                                                                                                               
Downloaded image 79a021b7-0cdb-dedb-9c81-ae32adcb0b45 (21.4 MiB)                                                                                                                              
Download 6 images                               [===========================================================================================================>] 100%  28.03MB  10.96MB/s     2s
Imported image 79a021b7-0cdb-dedb-9c81-ae32adcb0b45 (docker-layer@f17d81b4b692)
Imported image bdc38c41-d240-9538-95b1-5a8432852ab9 (docker-layer@b32474098757)
Imported image 923723d6-60c4-fdec-16f9-ed1e5970f8ee (docker-layer@8980cabe8bc2)
Imported image 36597173-2079-e74d-04c9-318e0151d5cb (docker-layer@58af19693e78)
Imported image 66b6b062-a045-32bd-b7c2-b0381f3d7c68 (docker-layer@a977782cf22d)
Imported image 0348076a-36c1-fc04-a0fb-bccdbf4c2fd8 (docker-layer@9c1e268980b7)
`

It seems to work, although, this is not working for more complex images. 

Best Regards
Paolo

**Comment by YanChii** [comment]
Hi @marcheschi 

We are watching Docker support for over two years.

And it seems that Docker in  LX zones on SmartOS is somewhat abandoned project. Even Joyent transitioned to VMs containing Kubernetes. I would not recommend to anyone using the LX+Docker in production. And as a consequence, it just too much work implementing something just for playing around.

We would however like to support Kubernetes. But it's also not trivial. Any help in this would be greatly appreciated (eg. building/updating images with cloud-init support, building loadballancer VM with api, etc).

Jan

PS: You can still create Danube Cloud images from Docker images by hand. I didn't try it but it should work:
- create LX VM in DC with any Joyent image
- add docker.io to imgadm, download image you want
- change the image of the created VM by hand using vmadm update
- run vmadm reprovision <vm_uuid> (undocumented by Joyent but it's present)
- go to DC GUI, create VM snapshot and image from it

**Comment by marcheschi** [comment]
Hi
Thank you for the very useful hints, I will try as soon as possible.
Best Regards
Paolo
