### ISSUE TITLE
Allow starting the already-started VM

### ISSUE THREAD

**Issue by YanChii** [erigones/esdc-ce#434]
When starting the VM that is for some reason running on a node but DC thinks it is stopped, it throws following error:
```
Got bad return code (0). Error: Unable to start VM: VM is already 'running'
```
It would be nicer to not throw error, just adjust the state in DC database. Because the desired state is already present. In current state, there's not many options how to recover from inconsistency between DB and current VM state (without using API or ssh).

The same probably applies on the opposite - stop vs stopped state (when DC thinks the VM is running).

**Comment by dn0** [comment]
<img width="366" alt="vm-refresh-status" src="https://user-images.githubusercontent.com/3155465/56948210-b7a21b00-6b2f-11e9-9774-9c30d9164d07.png">
@YanChii  Maybe we could add a small button so that users can trigger a VM status refresh manually.

**Comment by YanChii** [comment]
That would be perfect!
