### ISSUE TITLE
disk definition quota and mountpoint settings?

### ISSUE THREAD

**Issue by n1ete** [erigones/esdc-ce#444]
still exploring danube cloud ce and its possibilities....
is it possible to set a mount point and quota definitions for the second disk? as far as i understand actually the second disk size is derived from vm disk quota size and its mounted on $zonepool/$zoneuuid/data.

**Comment by YanChii** [comment]
Hi @n1ete,

You are probably talking about SunOS/LX zones. Here the second disk is a delegated dataset. That means that you can alter it's properties from *inside* of the zone. In another words, if you are root in that zone, you can change mountpoint, quota, create more sub-datasets, etc… all separately from the first disk.

Jan

**Comment by n1ete** [comment]
aah ok thanks! so i just use zfs tools as i used to?i do zlogin or ssh login into that zone and alter mountpoints and quotas as an admin but there is no way from the ui to do this?

**Comment by YanChii** [comment]
Overall quota is shared from the main dataset. But otherwise you have to set properties as a root in the zone. That's the point about being delegated.
But by default, it is mounted for you.

**Comment by YanChii** [comment]
But you still can build your own image that can include your custom scripts to do whatever you like.

**Comment by n1ete** [comment]
closed it for now, since i will not have much time for "homelabbing" till autumn/winter.... 
keep up the good work!
