### ISSUE TITLE
How to change IP of image server in web gui?

### ISSUE THREAD

**Issue by StevenWilliams** [erigones/esdc-ce#452]
Hi, so I changed the IP of the image server zone to 192.168.1.7 from a public IP then changed the web gui to use it's old IP (172.**.**.197), when I tried to press import from image repository on the web gui, it said an error 500. How can I change it to use the new IP?

**Comment by YanChii** [comment]
Hi,

I'm not sure I understand you completely. You had an installation where you have assigned public IPs for the management VMs and then you have changed it from public to private?

Next, if you have changed the web gui IP address without changing the configuration on nodes (`/opt/erigones/core/celery/local_config.py`), the `erigonesd` daemons on the node(s) will try to connect to the old gui IP and the nodes will appear as `unavailable` in the gui. Is that what you observe? That might be the reason for error 500.

If this is not a reason, please look into logs. Either into gui logs or into text logs inside `mgmt01` and search for traceback or error 500:
```
ssh root@<first_compute_node>
ssh root@<gui_ip>
less /opt/erigones/log/main.log
less /opt/erigones/log/mgmt.log
```
Jan

**Comment by YanChii** [comment]
If you still need help, please reopen this issue or contact us on [Gitter chat](https://gitter.im/erigones/DanubeCloud).
