### ISSUE TITLE
Hyperthreading not working

### ISSUE THREAD

**Issue by StevenWilliams** [erigones/esdc-ce#453]
Hi, is there a way to enable hyperthreading in illumos/danubecloud? I have a 2 x Xeon 2680v2 with 10 cores 20 threads each, yet the system only seems to be getting 20 cores (without the threads).

 Here's the details from the IRC log:
<stevenw99> Hi, how can I check to make sure multithreading is enabled? I'm getting a message saying the system has 40 cores but only 20 are enabled saying set boot_ncpus to change it (but mdb reports 40)
<stevenw99> multithreading is enabled in the bios
<stevenw99> it's a Xeon 2680v2
<stevenw99> I have 2 of them
<stevenw99> 10 cores, 20 threads each
<stevenw99> [root@node01 (dime-dallas1) ~]# psrinfo -pv
<stevenw99> The physical processor has 10 virtual processors (0-9)
<stevenw99>   x86 (GenuineIntel 306E4 family 6 model 62 step 4 clock 2800 MHz)
<stevenw99>  Intel(r) Xeon(r) CPU E5-2680 v2 @ 2.80GHz
<stevenw99> The physical processor has 10 virtual processors (10-19)
<stevenw99>   x86 (GenuineIntel 306E4 family 6 model 62 step 4 clock 2800 MHz)
<stevenw99>  Intel(r) Xeon(r) CPU E5-2680 v2 @ 2.80GHz
<jesse_> for two 12c/24t cpu system, psrinfo -pv lists:
<jesse_> The physical processor has 12 cores and 24 virtual processors (0-11 24-35)
<jesse_>   The core has 2 virtual processors (0 24)
<jesse_> ...
<jesse_> The physical processor has 12 cores and 24 virtual processors (12-23 36-47)
<jesse_>   The core has 2 virtual processors (12 36)
<jesse_> ...
<stevenw99> how would I enable multithreading then?
<jesse_> in bios, probably
<jesse_> /uefi
<jesse_> whatever is your poison
<stevenw99> it's already enabled there
<stevenw99> bios has been updated as well
<stevenw99> dell poweredge c6220 II
<jesse_> afaik there is no way to disable/enable HT cores in illumos itself (I may very well be wrong=
<jesse_> are you sure it didn't revert the enable when the bios was updated?
<stevenw99> I just checked, still enable

**Comment by YanChii** [comment]
Hi @StevenWilliams 

This is probably related to [OS-7662](https://smartos.org/bugview/OS-7662)

Try to add `smt_enabled=true` into `/usbkey/config` and reboot. In next Danube release, this will be added by default. Please let us know if it helped.

Jan

**Comment by YanChii** [comment]
New DC release is out and this setting is the default. It is set also during upgrade from previous versions.
If you still need help, please reopen this issue or contact us on [Gitter chat](https://gitter.im/erigones/DanubeCloud).
Cheers.
Jan
