### ISSUE TITLE
Canot add second disk to KVM VM

### ISSUE THREAD

**Issue by Kiwwiaq** [erigones/esdc-ce#474]
Hi,

After clean installation of v4.2 I cannot add second disk to KVM VM via GUI. I am adding disk in main DC created by head node installation process.

I have tried:
- with or without attached installation image
- installed and uninstalled VM
- upgraded to v4.2.1
- zones or different pool

No luck.

No error message in GUI. I have found this message in /opt/erigones/var/log/main.log on mgmt01.

`2020-01-05 15:02:34,984 DEBUG [vms.middleware]: "POST /servers/diskaddtest.ksc/settings/disk/" user="admin" dc="main" permissions=set(['user_admin', 'dns_admin', 'iso_admin', u'admin', 'image_admin', 'image_import_admin', 'template_admin', 'network_admin', 'super_admin', 'monitoring_admin'])
2020-01-05 15:02:34,996 INFO [gui.forms]: Calling API view POST vm_define_disk((u'diskaddtest.ksc', 2), data={'compression': u'lz4', 'boot': False, 'disk_id': 2, 'zpool': u'zones', 'model': u'virtio', 'size': 10240}) by user admin in DC main
2020-01-05 15:02:34,997 DEBUG [api.decorators]: "POST vm_define_disk (/servers/diskaddtest.ksc/settings/disk/)" user="admin" dc="main" permissions=set(['user_admin', 'dns_admin', 'iso_admin', u'admin', 'image_admin', 'image_import_admin', 'template_admin', 'network_admin', 'super_admin', 'monitoring_admin'])
2020-01-05 15:02:35,011 INFO [api.utils.views]: Called API view POST vm_define_disk((u'diskaddtest.ksc', 2), {'data': {'compression': u'lz4', 'zpool': u'zones', 'model': u'virtio', 'boot': False, 'disk_id': 2, 'size': 10240}}) by user admin in DC main 
	with response (400): {'status': 'FAILURE', 'result': {'image': [u'Cannot set image on disks other than first disk.']}, 'task_id': '1d1d1-6f75849b-6024-4d6f-ab97'}
`

Kind regards,
Ivan

**Comment by Kiwwiaq** [comment]
I have managed to "fix" this issue by some steps in GUI. The account I am logged in is super admin account admin. There is only one node, the head node.

I have noticed, that I can add second disk to KVM VM in admin virtual DC.

I have created new virtual DC called test and attached node, so I can create VM. I have faced the same issue and deleted this test DC.

In main DC, I have checked downloaded and attached OS images and changed the Linux VM image from Private, to Public access. I have attached group Admins to main DC. 

Now I can add second disk to to KVM VM in main DC. 

I have set Linux VM image back to Private access and detached group Admins from main DC.

I still can add second disk to to KVM VM in main DC. 

I have created new virtual DC one more time and added node. Now I can add second disk to to KVM VM in this test DC as well. I have deleted test DC.

Strange, but it works now as should.

**Comment by YanChii** [comment]
Hi @Kiwwiaq 
How does the GUI behave? You've said there's no error message... how does it look when it's not working? Did you try to create 2-disk VM or added disk to an existing VM. 

The error message `Cannot set image on disks other than first disk` is strange. Trying to add image to second disk is possible only using API, not through GUI. Anyway, I don't see the image defined in the output you have posted. Pls try looking also into `mgmt.log`. From what you're saying it has failed multiple times so there should be some errors in the logs.

I'm not able to replicate it on the clean install. I'll keep trying but if you had some steps how to hit this bug, it would make it much easier.

Thank you.

Jan

**Comment by Kiwwiaq** [comment]
Hi @YanChii 

I have been going through this "workflow" in GUI just after I finished installation, so step by step:
- login to GUI to default main DC
- change admin account password, name etc.
- define networks on Datacenter --> Networks screen
- import centos-8-kvm image and attach imported image on Datacenter --> Images screen
- add server by Servers --> Add Server --> enter name, vCPU, RAM, OS Type = Linux VM (no advanced configuration) --> [https://ibb.co/R2jwpgR](url)
- to "empty" new server definition
-- add first disk by Add Disk button (no advanced configuration)
-- add second disk by Add Disk button (no advanced configuration)

I am not fast enough to capture the screenshot, but as soon as I confirm Add Disk dialog, for a split second "Please Wait" status pops up showing progress. When all is good, [disk is added](https://ibb.co/gvWKZRh).

No error message means: 
"Please Wait" status pops up for a half of the second, then disappears with no additional pop up [back to Add Disk dialog](https://ibb.co/PmPKGpY).

**Comment by YanChii** [comment]
I'll try a new install with your steps. Keep us posted if it happens again.

**Comment by YanChii** [comment]
Hi Ivan,
Did it ever happen again? What you have described is pretty simple workflow and I've never seen such error when adding a second disk.
Jan

**Comment by Kiwwiaq** [comment]
Hi YanChii,

I have tried to replicate this several times and failed. I believe this was related to cosmic ray and could be closed as cannot replicate.
