### ISSUE TITLE
`Get latest version` button does not work with recent Firefox Nightly browser

### ISSUE THREAD

**Issue by jurajlutter** [erigones/esdc-ce#500]
There is (_probably_) a CORS issue with `Get latest version` button in `System>Maintenance>Update Danube Cloud on mgmt`. The button does not work as expected in recent Firefox Nightly (and probably also in other browsers in near future).

The error displayed in developer tools is:

```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://danubecloud.org/api/releases?system_version=4.2. (Reason: CORS request did not succeed).```

After entering a particular version (like, `v4.3`, the upgrade as such works).

More information on CORS can be found here:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors

**Comment by jurajlutter** [comment]
After CORS adjustments, this works.

**Comment by YanChii** [comment]
Fixed by adding `Access-Control-Allow-Origin: *` to the service.
