### ISSUE TITLE
pkgin operations fail in global zone with pkgsrc 2018Q4 and earlier

### ISSUE THREAD

**Issue by YanChii** [erigones/esdc-ce#505]
It is caused by changing the domain from `pkgsrc.erigones.com` to `pkgsrc.danube.cloud`. This was not (yet) covered by node update:
```
pkgin: Could not fetch https://pkgsrc.erigones.org/packages/SmartOS/2018Q4/x86_64/All/pkg_summary.gz
```

Quick workaround is this:
```
sed -i '' 's;pkgsrc.erigones.org;pkgsrc.danube.cloud;' /opt/local/etc/pkgin/repositories.conf
```

**Comment by YanChii** [comment]
The fix needs to be added to [node upgrade file](https://github.com/erigones/esdc-ce/tree/master/ans/upgrade/node) with appropriate version (e.g. `v4.4`).

**Comment by marcheschi** [comment]
This Affects also sunos zone images created before.
for example base-64-es that now is not usable as is, but every time we have to update repositories.
The workaround is to use a joyent image that uses the joyent repos.
Paolo

**Comment by YanChii** [comment]
Yes. For older images, it can be fixed by adding this script into `user-script` medatata (before anything else) during VM creation or later (later addition requires VM restart):
```
/usr/bin/sed -i '' -e 's/mirror.erigones.com/pkgsrc.joyent.com/' -e '/erigones/d' /opt/local/etc/pkgin/repositories.conf;
```
So the full script is:
```
/usr/bin/sed -i '' -e 's/mirror.erigones.com/pkgsrc.joyent.com/' -e '/erigones/d' /opt/local/etc/pkgin/repositories.conf; if [ ! -f /var/svc/provision_esdc ]; then   touch /var/svc/provision_esdc;   /usr/sbin/mdata-get root_authorized_keys > /root/.ssh/authorized_keys; /usr/sbin/mdata-get deploy-script > /var/svc/user-deploy-script && /usr/bin/bash /var/svc/user-deploy-script;   echo; fi;  /usr/sbin/mdata-get startup-script > /var/svc/user-startup-script && /usr/bin/bash /var/svc/user-startup-script;  exit 0
```

**Comment by YanChii** [comment]
Newer `base-64-es` images are already fixed. Existing VMs on older `base-64-es` images need to be fixed manually as described above.
