### ISSUE TITLE
Wrong DC version is shown on maintenance

### ISSUE THREAD

**Issue by marcheschi** [erigones/esdc-ce#508]
Hi
I noticed That after the updating of every cn and hn of DC to 4.3 , there is still the DC version= ce:4.3-rc2.
![image](https://user-images.githubusercontent.com/3910408/96562420-095cd900-12c1-11eb-85ff-2d08b5731eca.png)
![image](https://user-images.githubusercontent.com/3910408/96562499-20033000-12c1-11eb-875e-b38a11af96fb.png)

Paolo

**Comment by YanChii** [comment]
Pls check contents of `/opt/erigones/core/version.py` on that node(s). 
- if there's version `4.3`, just restart service daemon on that node: `esdc-service-control restart`
- if there's version `4.3-rcX`, the upgrade didn't finish successfully. Try again and/or see upgrade logs (in the `main` datacenter).

**Comment by marcheschi** [comment]
It is exactly the same version written in the web page:

But the usbkey is 4.3

[root@node03 (pacs)]#  cat /opt/erigones/core/version.py
__version__ = '4.3-rc1'
__edition__ = 'ce'
[root@node03 (pacs)]# cat /usbkey/version
esdc-ce-cn-4.3


[root@node02 (pacs) ~]# cat /opt/erigones/core/version.py
__version__ = '4.2'
__edition__ = 'ce'
[root@node02 (pacs) ~]# cat /usbkey/version
esdc-ce-cn-4.3

So something wrong with update or usbkey
Paolo

**Comment by YanChii** [comment]
Platform version is not directly related to DC software version. They upgrade separately (`esdc-git-update` vs `esdc-platform-upgrade`).

Try running `esdc-git-update v4.3` from console and see the output.

**Comment by marcheschi** [comment]
After running esdc-git-update v4.3 on all nodes  they update succesfully except one that went "unreachable"
I have a service offline
[root@node02 (pacs) ~]# svcs -xv
svc:/application/erigonesd:fast (?)
 State: maintenance since October 20, 2020 at 12:57:16 PM UTC
Reason: Method failed.
   See: http://illumos.org/msg/SMF-8000-8Q
   See: /var/svc/log/application-erigonesd:fast.log
Impact: This service is not running.
Starting nodes...
[ Sep 17 15:17:11 Method "start" exited with status 0. ]
[ Oct 20 12:52:16 Stopping because service restarting. ]
[ Oct 20 12:52:16 Executing stop method ("/opt/erigones/bin/erigonesd fast multi stop fast --pidfile="/opt/erigones/var/run/%n.pid""). ]
celery multi v3.1.25 (Cipater)
> Stopping nodes...
[ Oct 20 12:52:17 Method "stop" exited with status 0. ]
[ Oct 20 12:57:16 Method or service exit timed out.  Killing contract 125. ]

pAOLO

**Comment by YanChii** [comment]
`esdc-service-control status`
`esdc-service-control restart`

If some service reports maintenance state that is not solved by restart, run `svcadm clear <service_name>`.

**Comment by marcheschi** [comment]
Ok now after a restart all is online
the versions are aligned to 4.3 but I have still mgmt01 on 4.3 rc2
![image](https://user-images.githubusercontent.com/3910408/96596351-e6481e80-12ec-11eb-8fa2-b1f50f710e21.png)

I need to update  by pressing the button?
Paolo

**Comment by YanChii** [comment]
yes

**Comment by marcheschi** [comment]
No I still have some error when try to update I got
`error 0: Errore di rete (Errore sconosciuto)`
I do not find anything on the logs main.log or mgmt.log
I have some errors on mgmt.log but I think it is unrelated:
`[2020-10-20 14:35:11,740: ERROR/MainProcess] Task api.mon.vm.tasks.mon_vm_sla[9m1d2-47bf1fd0-bca9-4586-b2c8] raised unexpected: MgmtTaskException({'detail': u'Zabbix API Error when retrieving SLA (Error connecting to database.  [1])'},)
Traceback (most recent call last):
  File "/opt/erigones/envs/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/erigones/que/mgmt.py", line 86, in __call__
    return super(MgmtTask, self).__call__(tid, *args, **kwargs)  # run()
  File "/opt/erigones/envs/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/erigones/api/task/utils.py", line 382, in inner
    raise exc
MgmtTaskException: {'detail': u'Zabbix API Error when retrieving SLA (Error connecting to database.  [1])'}
`

**Comment by marcheschi** [comment]
Which is the server is trying to connect to?

**Comment by YanChii** [comment]
It looks like Zabbix cannot connect to its own postgres DB. Try restarting `mon01`. If it doesn't help, ssh into the VM and verify the postgresql DB.

**Comment by marcheschi** [comment]
restarting doesn't help because there is no space left on device

`[root@mon01 ~]# systemctl status postgresql-9.5.service
● postgresql-9.5.service - PostgreSQL 9.5 database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql-9.5.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2020-10-20 15:15:14 UTC; 1min 9s ago
     Docs: https://www.postgresql.org/docs/9.5/static/
  Process: 1091 ExecStart=/usr/pgsql-9.5/bin/pg_ctl start -D ${PGDATA} -s -w -t 300 (code=exited, status=1/FAILURE)
  Process: 1085 ExecStartPre=/usr/pgsql-9.5/bin/postgresql95-check-db-dir ${PGDATA} (code=exited, status=0/SUCCESS)

Oct 20 15:15:13 mon01.local systemd[1]: Starting PostgreSQL 9.5 database server...
Oct 20 15:15:13 mon01.local pg_ctl[1091]: < 2020-10-20 15:15:13.206 UTC >FATAL:  could not write lock file "postmaster.pid": No space left on device
Oct 20 15:15:14 mon01.local pg_ctl[1091]: pg_ctl: could not start server
Oct 20 15:15:14 mon01.local systemd[1]: postgresql-9.5.service: control process exited, code=exited status=1
Oct 20 15:15:14 mon01.local systemd[1]: Failed to start PostgreSQL 9.5 database server.
Oct 20 15:15:14 mon01.local systemd[1]: Unit postgresql-9.5.service entered failed state.
Oct 20 15:15:14 mon01.local systemd[1]: postgresql-9.5.service failed.
`
I have to find out why and where, in the meantime I can increase the space.
Paolo

**Comment by marcheschi** [comment]
/var/lib/pgsql/9.5/data/base is 6.6 GB

Is it normal ?

**Comment by YanChii** [comment]
Yes.
Zabbix stores all monitored items in the DB so after some time this size is normal. You can do a cleanup or grow the disk to keep older data.

Check also whether Zabbix itself is running (from DC GUI click on `Monitoring server`).

**Comment by marcheschi** [comment]
Yes it seems up and running 
![image](https://user-images.githubusercontent.com/3910408/96612603-3bd8f700-12fe-11eb-80a7-af829351aff0.png)

But the monitoring on the vms is not working, there are no graphs.
Paolo

**Comment by marcheschi** [comment]
Can help to give more vcpu and ram to mon01?
Paolo

**Comment by marcheschi** [comment]
Or I can restore a backup

**Comment by YanChii** [comment]
> Can help to give more vcpu and ram to mon01?
> Paolo

Just edit the VM the normal way.

**Comment by YanChii** [comment]
Try rebooting the `mgmt01` VM. Create a testing VM and see whether it gets created in Zabbix. See logs in GUI about Zabbix configuration push. Summary: see what works and what doesn't.
If something doesn't work, search log files for stack traces.

**Comment by marcheschi** [comment]
Ok now all started to work again and I see graphs.

Ntp needs some work .
But now it is late.
Thank you for the support

**Comment by YanChii** [comment]
Cool. 

Just FYI: time desync could cause that some commands to be ignored as obsolete.
