### ISSUE TITLE
lx zone stuck in deploying status 

### ISSUE THREAD

**Issue by marcheschi** [erigones/esdc-ce#509]
Hi
I have a zone stuck in deploying status.
The server is not deployed  but the task is still active.
How ca I cancel or abort that task
Thank you
Paolo

**Comment by YanChii** [comment]
To cancel a running task, it is recommended to do it from command line.
Before issuing the command, make sure the task is really not being processed. 
```
./es get /task           # find the pending task's uuid (visible also in GUI)
./es put /task/(task_id)/cancel
./es delete /task/(task_id) -force    # if the first command didn't succeed 
```
Use the last command with caution as it doesn't do a cleanup of what was already done.

https://docs.danubecloud.org/api-reference/api/task.html#task-task-id-cancel
https://docs.danubecloud.org/api-reference/api/task.html#delete--task-(task_id)

By the way, the VM deploy task has timeout of 10 minutes. So other option is to wait and most probably it resolves itself.

Jan

**Comment by marcheschi** [comment]
Hi
the timeout is not working , it is still there 
![image](https://user-images.githubusercontent.com/3910408/96887362-cfd4cb00-1484-11eb-8744-da63c83e096e.png)

**Comment by YanChii** [comment]
Ok. Now is the time for that CLI commands.

**Comment by marcheschi** [comment]
Ok this worked 
./es delete /task/9e9d1-e1a455f1-7b9e-46b7-9798 -force 
I think is worth creating a FAQ question.
Thank you again
Paolo

**Comment by YanChii** [comment]
Updated.
https://github.com/erigones/esdc-ce/wiki/FAQ
