### ISSUE TITLE
Grow mgmt01 VM RAM to 1,5 GB on new install

### ISSUE THREAD

**Issue by YanChii** [erigones/esdc-ce#518]
As preventive and performance-boost action, it will be better to have all newly deployed installation to have 1536 MB of RAM set for `mgmt01` VM.

The existing installations will not be touched and it is not needed for DC to function. 

But it is recommended to add RAM manually for `mgmt01` VM on existing installations.

**Comment by marcheschi** [comment]
Thank you for this alert, I updated to 2 GB and increased also the vcpu to be sure.

**Comment by marcheschi** [comment]
Where is (mgmt01) the task queue it appers i have a lot of slow down when I have a lot of tasks, is it possible to increase cpu/memory also here.

**Comment by YanChii** [comment]
The task queue server (rabbitmq) is inside the `mgmt01` VM. 
What kind of slow down? Is the GUI also slower? What is the approx number of "a lot of tasks"? :) What kind of tasks is mostly present when the slow down is observed?

**Comment by marcheschi** [comment]
The Task I have are snapshots and backups .
I have red errors on the gui when I try to destroy a zone or reboot.
I can be more precise when it happens again.

**Comment by YanChii** [comment]
Backups are performed sequentially one at a time on one compute node. Snapshots should be done immediately regardless the backup. When it happens again, see whether the node is not flapping (going up/down periodically). If that happens, it might suggest connection starving from erigonesd to the message queue.
