### ISSUE TITLE
Wiki Page DOCUMENTATION on Data Center Page

### ISSUE THREAD

**Issue by marcheschi** [erigones/esdc-ce#536]
Hi Is there a way to add documentation about the virtual Data-center? (network maps , compute nodes schema, logical connections,..) I think this could be useful, in order to see all at glance. I think could be enough a place to show a web page inside Datacenter administration, this could be also a page with markdown support like the Note in server setting.

**Comment by YanChii** [comment]
Sure, all docs are here https://github.com/erigones/esdc-docs/

They are pretty straightforward. All in markdown.

Pull requests are very welcome.

How to make local copy of docs web (using web server):
- pull the repo
- create python virtualenv from requirements [here](https://github.com/erigones/esdc-docs/blob/master/user-guide/requirements.txt) and [here](https://github.com/erigones/esdc-ce/blob/master/etc/requirements-mgmt.txt) (default is python2; python3 is in a separate branch, not merged to master yet)
- activate env, `cd esdc-docs`
```
git pull
make clean
make html
```
- point nginx or any other browser to serve the static content, e.g.
```
server {
    listen       80;
    server_name  localhost;
    root         /data/docs.danube.cloud/html;

    location = / {
        return 302 https://localhost/user-guide/esdc/index.html;
    }
}
```
