### ISSUE TITLE
VMS_DISK_IMAGE_DEFAULT is applied also to second disk

### ISSUE THREAD

**Issue by marcheschi** [erigones/esdc-ce#551]
Hi 
I'm unable to add disk to VM (bhyve or kvm)
Paolo

**Comment by YanChii** [comment]
I'm unable to replicate it. Not even on (yet unreleased) `v4.5-rc1`.
Can you pls provide more info?
Jan

**Comment by marcheschi** [comment]
I've sent you a video on gitter to show the behavior

**Comment by marcheschi** [comment]
The error is:

`2021-06-24 11:52:17,817 INFO [api.utils.views]: Called API view POST vm_define_disk((u'ubuntu201', 2), {'data': {'compression': u'lz4', 'zpool': u'zones', 'model': u'virtio', 'boot': False, 'disk_id': 2, 'size': 10240}}) by user paolo in DC main 
	with response (400): {'status': 'FAILURE', 'result': {'image': [u'Cannot set image on disks other than first disk.']}, 'task_id': '9d9d1-c7c6ad26-7f90-495b-a9ba'}
`

**Comment by YanChii** [comment]
You've probably set a default VM image in datacenter settings. It is applied also to a second disk, which is obviously a bug because second disk cannot have image.
For now, pls set `VMS_DISK_IMAGE_DEFAULT` value to `(none)`.
Jan

**Comment by marcheschi** [comment]
Yes Right This solved the problem.
Thank you
Paolo
