### ISSUE TITLE
VM with BIG disk created but DC thinks it's not. 

### ISSUE THREAD

**Issue by marcheschi** [erigones/esdc-ce#561]
I have a zpool of 3 TB and a size coefficient of 0.90 , I want to create a bhyve vm with the new ubuntu-focal-uefi image with 2 TB size, but when I deploy the vm it deploys it on the node but the bui is complaining with:
Got bad return code (1). 
Error: Successfully created VM jcare-pgsqlpi1 
cannot set property for 'zones/jcare-pgsqlpi1/disk0': size is greater than available space 
Successfully started VM jcare-pgsqlpi1

In order to reproduce it :
I have a node with 3 TB /zones zpool
I have increased the size coefficient to 0.90 in order to use more space (was 0.60)
I created a new VM with : "bootrom": "uefi" and disk with vm image "ubuntu-focal-uefi"   with size of 2TB compression lz4
![image](https://user-images.githubusercontent.com/3910408/136192209-f028501c-a990-4393-aa20-69bfad6d2f7a.png)
when I try to deploy, I got:
![image](https://user-images.githubusercontent.com/3910408/136192446-28a5efd3-50ca-465c-a2a4-a985c4c2aa4c.png)
The Vm is created on the node and I can connect to it, but is not shown on the BUI.
Thank you
Paolo

**Comment by marcheschi** [comment]
I tried also to increase the size coefficient to 0.95 but the result is the same., since the vm appears not created is not possible to refresh it to reload the configuration.

**Comment by marcheschi** [comment]
This is not a problem if I create a Sunos zone.

**Comment by YanChii** [comment]
Marking as bug. It should not report success.

**Comment by YanChii** [comment]
Do you have enough free (unreserved) space in the ZFS pool to create 2TB disk?
`zfs list`

**Comment by marcheschi** [comment]
![image](https://user-images.githubusercontent.com/3910408/136343848-3e22f31b-15c6-4a1c-b5e4-8400cd5dd50f.png)

**Comment by marcheschi** [comment]
Instead, if I add a 2 TB disk it works
![image](https://user-images.githubusercontent.com/3910408/136389960-969c0bab-5b69-4901-beea-8d8ef249acb5.png)

**Comment by YanChii** [comment]
I'm trying to replicate it but no success yet. Could you pls look into `/opt/erigones/log/main.log` at `mgmt01.local` and search for string `Creating new VM`? You should see the full json that was used to create the VM. Pls post it here.
You can also try to test-create the VM by hand using that json directly with `vmadm`.
