### ISSUE TITLE
Any ISO Releases?

### ISSUE THREAD

**Issue by lonnietc** [erigones/esdc-ce#574]
Hello,

I was to use an ISO to install the HN and CN on some servers but all I can find are the ".img" files.

Are there any other solutions?

**Comment by YanChii** [comment]
Hi @lonnietc ,

There are `.img` files for USB sticks that can be used to install/run the Danube. You can also create your own PXE server to do the same (like [this](https://docs.danube.cloud/user-guide/howto/pxe-zone.html)).
Besides that, you can download specially crafted netinstall ISO images that can do a PXE boot for you from our servers over internet. You can find them here together with Readme:
https://download.danube.cloud/pxe/

In case of ISO PXE, disk install is recommended (you probably don't want to PXE boot over internet after every reboot).

Cheers.

Jan
