### ISSUE TITLE
not working  changing node name on sun vm

### ISSUE THREAD

**Issue by marcheschi** [erigones/esdc-ce#576]
Hi
I tried to change the nodename/hostname on the interface for a SUN os vm, but when restarting the  vm the cloud init does not change the nodename.
I had to edit by hand /etc/nodename.

The image I used is
minimal-64-21.4

**Comment by YanChii** [comment]
Hi,
SunOS zones don't use cloud-init. They use zoneinit created (AFAIK) by Joyent. The zoneinit does run only at first start of the zone.
Therefore it doesn't change hostname or resolvers later. Unfortunately by design.
You need to change it manually.
Jan

**Comment by marcheschi** [comment]
Ok it's clear 
thank you
Paolo
