### ISSUE TITLE
`danubecloud.org` seems to be down...

### ISSUE THREAD

**Issue by dillfrescott** [erigones/esdc-ce#587]
![Screenshot 2022-12-09 080519](https://user-images.githubusercontent.com/56714680/206708972-3a6bcde4-d140-4c05-95e4-a5d5a73aaf94.png)

**Comment by YanChii** [comment]
Thank you @dillfrescott for pointing this out.

It was a redirection problem after recent changes. Monitoring didn't catch it up.

It's fixed now.

Jan
