### ISSUE TITLE
danube cloud development status

### ISSUE THREAD

**Issue by jbarfield** [erigones/esdc-ce#593]
What is the current development status of danube cloud?

I do not see any commit history since 2022. Is development still active?

Where can I get more information? Is there a mailing list?

**Comment by YanChii** [comment]
Hi @jbarfield 

DC development not very active, unfortunately. Recently we've created new [platform](https://download.danube.cloud/esdc/factory/platform/) in https://github.com/erigones/illumos-joyent (upgrade using `esdc-platform-upgrade 20240627T213014Z` if you have diskinstall).

You can get more info in our matrix channel (former gitter) https://gitter.im/erigones/DanubeCloud

Jan
