### ISSUE TITLE
Add support for erigones image tags into POST image_manage

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#7]
API calls related to image imports (either POST image_manage or POST imagestore_image_manage) ignore our image tags (deploy, resize and erigones attributes in the tags metadata).

**Comment by dn0** [comment]
There are several problems that this issue tries to solve. 

1. When creating images via esDC, the `resize`, `deploy` and `tags` are not saved on the local image server (you can create an image and check the manifest on the image server or via HTTP)
   * this was solved by updating the `Image.build_manifest()` method - commit 5e84c6f54109f046659b5ffbacc1e69ad2b18ee4

2. Our custom image attributes (`resize`, `deploy` and `tags`) are not read  when importing images from remote location:
   * When importing through the API (either via POST image_manage or via POST imagestore_image_manage), the attributes in the remote image manifest should work as default values and can be optionally overridden by specifying them in the json sent to the server. You can check this by importing an image with e.g. resize=true and the image will have resize=false, because it ignores the value in the manifest. Solved by updating the `ImportImageSerializer.validate_manifest_url()` and `ImageView.post()` in commit 0a593a9bc88faac90c1a49ced9eb84a6c40655f4

   * When importing through the GUI there are two possible ways to achieve this:
        -  *Import image from URL*, where most of the attributes are overridden by user by default (nothing we can do here)
        -  *Import image from repository*, where default image attributes can be read from the remote manifest, because this is stored in cache - support for custom image attributes (`resize`, `deploy` and `tags`) was added by updating the `ImageStoreObject.web_data` property in commit 0a593a9bc88faac90c1a49ced9eb84a6c40655f4 - You can see that the import modal has the checkbox for the `resize` attribute checked after the commit.

**Comment by mbag** [comment]
I reviewed and tested changes, it's OK to merge.

**Comment by dn0** [comment]
@mbag Thanks, awaiting approval on PR #9

**Comment by mbag** [comment]
@dn0 sorry, I didn't check where I was commenting.
