### ISSUE TITLE
Rename compute node "offline" status to "maintenance" 

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#87]

**Comment by mbag** [comment]
In addition to renaming we need to change the color of the maintenance tag in the GUI.

**Comment by mbag** [comment]
As part of this fix we should change the color of the label from red to something else, since red represents that something is wrong. 
@dn0  can you please specify the color for the "maintenance" label?

**Comment by dn0** [comment]
@mbag Maybe we can switch the offline color with the unreachable color (orange for maintenance and red for unreachable....)

**Comment by dn0** [comment]
@mbag On the other hand, maybe we should keep the colors as they were/are (red for maintenance, orange for unreachable), because:

 - this would be consistent with what the user is used to
 - it would be also consistent with the VM status codes (meaning: red VM is stopped == red node is maintenance => I can stop the physical node)

**Comment by mbag** [comment]
@dn0 I already changed scss, but it can be reverted. I would reserve red color for really bad situation, and I don't think maintenance is the case which deserves red color.

**Comment by dn0** [comment]
@mbag Having a node unreachable sounds like a really bad situation to me :) But, OK, let's keep the unreachable color (orange, to be backward compatible) and change the maintenance color to something else, e.g.:

- `#684688`
- `#474688`
- `#b98348`

**Comment by mbag** [comment]
@dn0 I was ok with unreachable being red. I was referring to the statement, that maintenance should be kept red and unreachable orange (this comment: https://github.com/erigones/esdc-ce/issues/87#issuecomment-289294675)

**Comment by dn0** [comment]
I understand. But I was wrong in my first comment. Since humans "read" colors, we should **not** re-use the same color for a different situation. That's why I changed my mind and prefer to keep the unreachable state orange (as it was) - there is nothing wrong with that color. And if you don't like the maintenance (offline) state to be red we can change that to something else.

**Comment by mbag** [comment]
@dn0  OK, I switched "maintenance" to purple, i.e. the first color of the three suggested.
