### ISSUE TITLE
Automatic Zabbix host group creation and updates

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#93]
Dynamically synchronize host groups in Zabbix according to monitoring hostgroups setting and DC association in esdc.

**Comment by secult** [comment]
TODO:

- [ ] test API in vm_define
- [ ] test API in templates
- [ ] discuss cache expiration (_MonBaseView.get)
- [ ] discuss adding _*args_ into mon_template_list and mon_hostgroup_list
- [ ] discuss new regexes for monitoring hostgroups fields
- [ ] discuss changing monitoring templates behavior to match this change
