### ISSUE TITLE
Alerting management (Zabbix actions)

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#94]
Configure Zabbix actions via esdc API/GUI.

Consider removal of empty hostgroups after this task is implemented .

**Comment by secult** [comment]
- Node related alerting should be set automatically only to superadmins
- VMs have tags ->   User groups should be mapped on these tags, not directly to VMs. Tags will be synchronized to a host group.

**Comment by secult** [comment]
Create:
just send user group list, host group list. Everything else will be added by default.
In GUI/List Actions:
Cache the asynchronous list result for a long time, the list will not change often and when yes, the cache should be invalidated when needed
