### ISSUE TITLE
Fix blank page on 403 (Forbidden)

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-ce#96]

**Comment by mbag** [comment]
@dn0 
We have two options here, currently we are returning `HttpResponseForbidden()` when there is permission problem with user's request. The solution is to render 403 template, that will be also added as part of the fix. The occurrences of HttpResponseForbidden will be substituted with:
`return HttpResponseForbidden(render(request, '403.html'))`

Another option is to substitute `return HttpResponseForbidden()` with `raise PermissionDenied` and let Django handle the template (I've tried it, the correct custom template is found and returned in the response).
